### ISSUE TITLE
Introduction text missing spacing when viewed in table size

### ISSUE THREAD

**Issue by tristanmarsh** [gracemarsh/responsive-profile-from-mockups#3]
Hi! This site looks ✨ great! ✨

I just noticed one issue where the text touches the edge of the screen on table size.
<img width="998" alt="Screen Shot 2021-03-03 at 3 22 12 pm" src="https://user-images.githubusercontent.com/3328024/109752576-c3cbf780-7c34-11eb-9c7c-ce673a0ae272.png">

The correct spacing is applied in other areas like the portfolio gallery as shown in the screenshot.
<img width="998" alt="Screen Shot 2021-03-03 at 3 21 56 pm" src="https://user-images.githubusercontent.com/3328024/109752585-c75f7e80-7c34-11eb-9371-906b42dbb51b.png">

It looks like the .wrapper class needs a margin of around `2rem`, and then for the margin on the image inside the header to be removed.

**Comment by gracemarsh** [comment]
Fixed
